name: Awesome CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11 so that I can run java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        working-directory: .
        run: gradle build -x test

      - name: Run test, please!
        working-directory: .
        run: gradle test

  system-test:
    runs-on: ubuntu-latest
    needs: build-and-test-please
    steps:
      - uses: actions/checkout@v1

      - name: Run the server
        working-directory: .
        run: |
          chmod +x gradlew
          docker-compose up --build -d

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - run: pip install pytest requests

      - name: Run system tests
        working-directory: .
        run: pytest

      - name: Stop the server
        working-directory: .
        run: docker-compose down